services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: waresys
      POSTGRES_PASSWORD: waresys
      POSTGRES_DB: waresys
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports: ["6379:6379"]

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file: ./.env
    depends_on: [db, redis]
    ports: ["8000:8000"]
    volumes:
    - ./api/app:/app/app
    - ./uploads:/app/uploads

      

  worker:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    env_file: ./.env
    command: celery -A app.tasks:celery_app worker --loglevel=INFO --concurrency=2
    depends_on: [api, db, redis]
    volumes:
      - ./api/app:/app/app
      - ./uploads:/app/uploads

volumes:
  dbdata:
