version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=waresys
      - POSTGRES_PASSWORD=waresys
      - POSTGRES_DB=waresys
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-alpine

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg://waresys:waresys@db:5432/waresys
      - REDIS_URL=redis://redis:6379/0

  worker:
    build: .
    # This command is now correct and points to your central celery_app.py file
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+psycopg://waresys:waresys@db:5432/waresys
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data: