version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: waresys
      POSTGRES_PASSWORD: waresys
      POSTGRES_DB: waresys
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env                # ✅ ensure Alembic can see DATABASE_URL
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./alembic.ini:/app/alembic.ini
    ports:
      - "8000:8000"
    depends_on:
      - db

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    command: celery -A app.tasks:celery_app worker --loglevel=INFO --concurrency=2
    depends_on:
      - api
      - db
      - redis
    volumes:
      - ./app:/app/app        # keep same mount as api for consistency
      - ./uploads:/app/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api

volumes:
  dbdata:
  